# Generated by Django 3.2.9 on 2023-01-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20230113_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='billboxcode',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
