# Generated by Django 3.2.9 on 2023-01-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_address_billboxcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
